import { makeStyles } from '@material-ui/core/styles';

const useStyles = makeStyles((theme) => ({
  backDrop: {
    backgroundColor: 'rgba(115, 115, 115, 0.68)',
    position: 'fixed',
    top: 0,
    width: '100%',
    height: '100vh',
    zIndex: 10,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  backdropLoading: {
    position: 'fixed',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: 7,
    display: 'grid',
    placeContent: 'center',
  },
  loading: {
    zIndex: 9,
    display: 'grid',
    placeContent: 'center',
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 20,
    boxShadow:
      'rgba(0, 0, 0, 0.25) 0px 54px 55px, rgba(0, 0, 0, 0.12) 0px -12px 30px, rgba(0, 0, 0, 0.12) 0px 4px 6px, rgba(0, 0, 0, 0.17) 0px 12px 13px, rgba(0, 0, 0, 0.09) 0px -3px 5px',
  },
  card: {
    boxSizing: 'border-box',
    position: 'relative',
    width: 570,
    backgroundColor: '#F9F9F9',
    borderRadius: 30,
    boxShadow: '0px 4px 10px rgba(0, 0, 0, 0.05)',
    padding: '40px 70px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    '& > button': {
      all: 'unset',
      cursor: 'pointer',
      marginTop: 'auto',
      padding: '11px 40px',
      backgroundColor: '#D13201',
      borderRadius: 20,
      color: 'white',
      fontFamily: 'Montserrat',
      fontWeight: 'bold',
      fontSize: 14,
      marginTop: 90,
    },
    '& > img': {
      position: 'absolute',
      right: 50,
      cursor: 'pointer',
    },
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    gap: 14,
    fontFamily: "'Baloo 2', cursive",
    fontWeight: 400,
    fontSize: 40,
    width: '100%',
    color: 'rgba(18, 18, 18, 0.8)',
    '& > img': {
      height: 48,
    },
  },
  form: {
    alignSelf: 'center',
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    gap: 30,
    '& > *': {
      padding: 0,
    },
  },
  inputs: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    gap: 15,
  },
  containerInput: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    '& > label': {
      fontSize: 16,
      color: '#393C40',
      marginLeft: 16,
      fontFamily: 'Montserrat',
      fontWeight: '600',
    },
  },
  input: {
    '&>*': {
      height: 40,
      width: 360,
    },
  },
  erro: {
    position: 'absolute',
    width: 360,
    borderRadius: 5,
    backgroundColor: 'rgba(251, 59, 0, 0.2)',
    padding: '10px 12.5px',
    color: '#AA320F',
    fontFamily: 'Montserrat',
    fontSize: 14,
    fontWeight: 500,
    bottom: 110,
  },
  sucesso: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    height: '100%',
    justifyContent: 'center',
    marginTop: 50,
    '& > p': {
      textAlign: 'center',
      fontFamily: 'Montserrat',
      fontSize: 20,
      fontWeight: 600,
      color: '#525459',
    },
    '& > button': {
      all: 'unset',
      cursor: 'pointer',
      marginTop: 'auto',
      padding: '11px 40px',
      backgroundColor: '#D13201',
      borderRadius: 20,
      color: 'white',
      fontFamily: 'Montserrat',
      fontWeight: 'bold',
      fontSize: 14,
    },
  },
}));

export default useStyles;
