import { makeStyles } from '@material-ui/core/styles';

const useStyles = makeStyles((theme) => ({
  backdrop: {
    position: 'fixed',
    top: 0,
    width: '100%',
    height: '100vh',
    backgroundColor: 'rgba(115, 115, 115, 0.68)',
    zIndex: 10,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  backdropLoading: {
    position: 'fixed',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: 7,
    display: 'grid',
    placeContent: 'center',
  },
  loading: {
    zIndex: 9,
    display: 'grid',
    placeContent: 'center',
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 20,
    boxShadow:
      'rgba(0, 0, 0, 0.25) 0px 54px 55px, rgba(0, 0, 0, 0.12) 0px -12px 30px, rgba(0, 0, 0, 0.12) 0px 4px 6px, rgba(0, 0, 0, 0.17) 0px 12px 13px, rgba(0, 0, 0, 0.09) 0px -3px 5px',
  },
  card: {
    boxSizing: 'border-box',
    width: 570,
    backgroundColor: '#F9F9F9',
    borderRadius: 30,
    boxShadow: '0px 4px 10px rgba(0, 0, 0, 0.05)',
    position: 'relative',
  },
  botaoFechar: {
    zIndex: 11,
    position: 'absolute',
    top: 40,
    right: 40,
    cursor: 'pointer',
  },
  bannerProduto: {
    width: '100%',
    height: 240,
    borderTopRightRadius: 30,
    borderTopLeftRadius: 30,
    objectFit: 'cover',
  },
  iconeRestaurante: {
    boxSizing: 'border-box',
    width: 100,
    height: 100,
    borderRadius: '50%',
    backgroundColor: 'white',
    border: '4px solid white',
    position: 'absolute',
    right: 70,
    top: 'calc(40% - 50px)',
  },
  conteudoCard: {
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    padding: '35px 50px',
    gap: 20,
    height: '100%',
    '& > h2': {
      fontFamily: 'Montserrat',
      fontWeight: 600,
      fontSize: 36,
      color: '#525459',
      marginTop: 0,
      marginBottom: 0,
    },
  },
  barraCard: {
    display: 'flex',
    width: '100%',
    justifyContent: 'space-between',
  },
  itemBarra: {
    display: 'flex',
    alignItems: 'center',
    gap: 5,
    fontFamily: 'Montserrat',
    '& > p': {
      fontWeight: '600',
      fontSize: 14,
    },
    '& > span': {
      fontWeight: '400',
      fontSize: 14,
    },
  },
  containerDescPreco: {
    width: '100%',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 35,
    gap: 28,
    '& > p': {
      width: '50%',
      fontFamily: 'Montserrat',
      fontSize: 14,
      color: 'rgba(34, 34, 34, 0.87)',
    },
  },
  containerPreco: {
    padding: '12px 39px',
    width: 'max-content',
    borderRadius: 4,
    background:
      'linear-gradient(0deg, rgba(13, 138, 79, 0.1), rgba(13, 138, 79, 0.1)), #FFFFFF',
    fontFamily: 'Montserrat',
    color: '#006335',
    fontSize: 24,
    fontWeight: 600,
  },
  botoes: {},
  conteudoAdicionar: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    height: 280,
  },
  mensagemSucesso: {
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
    marginTop: 30,
    '& > p': {
      fontFamily: 'Montserrat',
      color: '#525459',
      fontSize: 20,
      fontWeight: 600,
      margin: 0,
    },
    '& > img': {
      height: 102,
    },
  },
  botaoRevisao: {
    marginTop: 'auto',
    all: 'unset',
    cursor: 'pointer',
    fontFamily: 'Montserrat',
    fontWeight: 600,
    fontSize: 13,
    color: '#525459',
    textDecorationLine: 'underline',
    '&:disabled': {
      display: 'none',
    },
  },
}));

export default useStyles;
